server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，职责就是维护服务实例，不需要去检索实例
    fetch-registry: false
    service-url:
      #单机就是7001自己
      #default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/